baseURL = "https://hannahmm.github.io/groupalarm/"
languageCode = "en-us"
publishDir  = "docs"
title = "GroupAlarm Handbuch"
defaultContentLanguage = "de"
canonifyURLs = true
theme = "hugo-theme-docdock"

[params]
themeStyle = "original"
themeVariant = "default"
defaultContentLanguageInSubdir= true
enableMissingTranslationPlaceholders = true

disableHomeIcon = true
disableNavChevron = true
disableSearch = false


[imaging]
anchor = "center"



[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]

[Languages.de]
title = "GroupAlarm Handbuch"
languageName = "de"

[Languages.en]
title = "GroupAlarm Manual"
languageName = "en"

[Languages.fr]
title = "GroupAlarm Manuel"
languageName = "fr"

[Languages.it]
title = "GroupAlarm Manuale"
languageName = "it"

